# Choose stable linux environment
FROM --platform=linux/amd64 ubuntu:24.04 

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    wget \
    python3 \
    python3-pip \
    valgrind \
    autoconf \
    automake \
    libtool \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Install Protobuf 3.12.4
RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v3.12.4/protobuf-cpp-3.12.4.tar.gz && \
    tar -xzf protobuf-cpp-3.12.4.tar.gz && \
    cd protobuf-3.12.4 && \
    ./configure && \
    make -j$(nproc) && \
    make install && \
    ldconfig && \
    cd / && \
    rm -rf protobuf-3.12.4 protobuf-cpp-3.12.4.tar.gz

# Install libbid
RUN git clone https://github.com/xmake-mirror/IntelRDFPMathLib.git && \
    cd IntelRDFPMathLib/LIBRARY && \
    make CC=gcc && \
    cp libbid.a /usr/local/lib/ && \
    cd / && \
    rm -rf IntelRDFPMathLib

WORKDIR /workspace