name: Project Orion CI
on:
  pull_request:
jobs:
  clang-format:
    name: Check C++ Code Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format-17

      - name: Format code
        run: python3 scripts/utilities/fix_formatting.py

      - name: Check for differences
        run: git --no-pager diff --color --exit-code

  build-dev:
    name: Build Trading Engine Binary
    runs-on: ubuntu-latest
    needs: [clang-format]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          cmake --preset dev
          cmake --build --preset dev

  run-test:
    name: Test Trading Engine
    runs-on: ubuntu-latest
    needs: [clang-format]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and run tests
        run: |
          cmake --preset test
          cmake --build --preset test
          cd build_test && ctest
